### PR TITLE
Add TI CC13x0 platform documentation

### PR DESCRIPTION
**Pull request by nanosonde**
This PR adds TI CC13x0 platform documentation.

### CODE REVIEW

**Comment by ivankravets** [comment]
PlatformIO will generate it automatically the only platform is added to the registry

**Comment by nanosonde** [comment]
It was a draft PR and not the real documentation was not added yet. 
So how can I add the CC13x0 docs?

**Comment by ivankravets** [comment]
> So how can I add the CC13x0 docs?

the system will do this automatically :)

**Comment by nanosonde** [comment]
You mean that it automatically adds ticc13x0.rst?

**Comment by ivankravets** [comment]
We run the script locally and it generates docs.

**Comment by nanosonde** [comment]
Ok, so it takes the provided meta information from the JSON files and generates the docs?

But how can I add some extra info like mentioning that it is experimental for example. Or add other hints?

**Pull request closed without merging**
