### PR TITLE
Create alorium_hinj.rst

### PR DESCRIPTION
**Pull request by jpecor**
doc file for Alorium Technology Hinj board

### CODE REVIEW

**Comment by ivankravets** [comment]
Hi ;)

We generate docs for boards automatically using their manifests. Please make PR to https://github.com/platformio/platform-atmelavr/tree/develop/boards


You can use this template https://github.com/platformio/platform-atmelavr/blob/develop/boards/alorium_xlr8.json

**Comment by jpecor** [comment]
@ivankravets  - Ok.  So you automatically generate the doc file from the board manifest, as well?

**Comment by ivankravets** [comment]
Yes ;) After each new release of dev/platform. I'll try to release Atmel AVR dev/platform next week. 
We have only 1 change :) https://github.com/platformio/platform-atmelavr/commits/develop

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platformio-docs/commit/93ec1f2dbb7a623261650e8ca879123e5866bb1c

**Comment by ivankravets** [comment]
Also, new release is out https://github.com/platformio/platform-atmelavr/releases/tag/v1.12.3

Does it work?

**Pull request closed without merging**
