### PR TITLE
Update upload_speed.rst

### PR DESCRIPTION
**Pull request by ijash**

### CODE REVIEW

**Comment by valeros** [comment]
Hi @ijash, thanks for the PR. Please see my comments below:

**Comment by ijash** [comment]
> Hi @ijash, thanks for the PR. Please see my comments above:
which one?

**Review by valeros — CHANGES_REQUESTED** [review]

**Comment by valeros** [comment]
> hi, which one?

They should be visible now as review comments

**Comment by ijash** [comment]
@valeros please review

**Pull request merged**
